In [13]:
#ABDUL RAFAY / 2022F-BSE-197 / LAB 05 / TASK 01:
# Importing necessary libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
# Data from the table
data = {
    "Gender": ["male", "male", "male", "male", "female", "female", "female", "female"],
    "Height": [6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75],
    "Weight": [180, 190, 170, 165, 100, 150, 130, 150],
    "Foot_Size": [12, 11, 12, 10, 6, 8, 7, 9]
}
# Creating a DataFrame
df = pd.DataFrame(data)
# Encoding the Gender column
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
# Splitting the features and target
X = df[["Height", "Weight", "Foot_Size"]]
y = df["Gender"]
# Training the Decision Tree Classifier
clf = DecisionTreeClassifier()
clf.fit(X, y)
# Making predictions on the training data
y_pred = clf.predict(X)
# Predict function for a new input
def predict_gender(height, weight, foot_size):
    # Input data as a DataFrame with column names
    input_data = pd.DataFrame([[height, weight, foot_size]], columns=["Height", "Weight", "Foot_Size"])
    prediction = clf.predict(input_data)
    gender = label_encoder.inverse_transform(prediction)
    return gender[0]
print("ABDUL RAFAY / 2022F-BSE-197 / LAB 05 / TASK 01:\n")
# Example: Predicting for a new entry
new_height = float(input("Enter Height: "))
new_weight = int(input("Enter Weight: "))
new_foot_size = int(input("Enter Foot Size: "))
predicted_gender = predict_gender(new_height, new_weight, new_foot_size)
print(f"The predicted gender is: {predicted_gender}")
# Generating the confusion matrix
conf_matrix = confusion_matrix(y, y_pred)
print("Confusion Matrix:")
print(conf_matrix)
# Calculating model accuracy
accuracy = accuracy_score(y, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

ABDUL RAFAY / 2022F-BSE-197 / LAB 05 / TASK 01:



Enter Height:  6.5
Enter Weight:  200
Enter Foot Size:  12


The predicted gender is: male
Confusion Matrix:
[[4 0]
 [0 4]]
Model Accuracy: 1.00


In [15]:
#ABDUL RAFAY / 2022F-BSE-197 / LAB 05 / TASK 02:
# Importing necessary libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
# Data from the table
data = {
    "Gender": ["male", "male", "male", "male", "female", "female", "female", "female"],
    "Height": [6.20, 5.95, 5.70, 6.05, 5.15, 5.60, 5.30, 5.65],
    "Weight": [200, 180, 165, 175, 105, 125, 120, 140],
    "Foot_Size": [14, 12, 11, 10, 6, 7, 6, 8]
}
# Creating a DataFrame
df = pd.DataFrame(data)
# Encoding the Gender column
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
# Splitting the features and target
X = df[["Height", "Weight", "Foot_Size"]]
y = df["Gender"]
# Training the Decision Tree Classifier
clf = DecisionTreeClassifier()
clf.fit(X, y)
# Making predictions on the training data
y_pred = clf.predict(X)
# Predict function for a new input
def predict_gender(height, weight, foot_size):
    # Input data as a DataFrame with column names
    input_data = pd.DataFrame([[height, weight, foot_size]], columns=["Height", "Weight", "Foot_Size"])
    prediction = clf.predict(input_data)
    gender = label_encoder.inverse_transform(prediction)
    return gender[0]
print("ABDUL RAFAY / 2022F-BSE-197 / LAB 05 / TASK 02:\n")
# Example: Predicting for a new entry
new_height = float(input("Enter Height: "))
new_weight = int(input("Enter Weight: "))
new_foot_size = int(input("Enter Foot Size: "))
predicted_gender = predict_gender(new_height, new_weight, new_foot_size)
print(f"The predicted gender is: {predicted_gender}")
# Generating the confusion matrix
conf_matrix = confusion_matrix(y, y_pred)
print("Confusion Matrix:")
print(conf_matrix)
# Calculating model accuracy
accuracy = accuracy_score(y, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

ABDUL RAFAY / 2022F-BSE-197 / LAB 05 / TASK 02:



Enter Height:  7
Enter Weight:  220
Enter Foot Size:  11


The predicted gender is: male
Confusion Matrix:
[[4 0]
 [0 4]]
Model Accuracy: 1.00


In [19]:
#ABDUL RAFAY / 2022F-BSE-197 / LAB 05 / TASK 03:
# Importing necessary libraries
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
# Data from the table
data = {
    "Gender": ["male", "male", "male", "male", "female", "female", "female", "female"],
    "Height": [6.00, 5.92, 5.58, 5.92, 5.00, 5.50, 5.42, 5.75],
    "Weight": [180, 190, 170, 165, 100, 150, 130, 150],
    "Foot_Size": [12, 11, 12, 10, 6, 8, 7, 9]
}
# Converting data to numpy arrays
gender = np.array(data["Gender"])
height = np.array(data["Height"])
weight = np.array(data["Weight"])
foot_size = np.array(data["Foot_Size"])
# Encoding the Gender column
label_encoder = LabelEncoder()
gender_encoded = label_encoder.fit_transform(gender)
# Combining features into a single numpy array
X = np.column_stack((height, weight, foot_size))
y = gender_encoded
# Training the Decision Tree Classifier
clf = DecisionTreeClassifier()
clf.fit(X, y)
# Making predictions on the training data
y_pred = clf.predict(X)
# Predict function for a new input
def predict_gender(height, weight, foot_size):
    # Input data as a numpy array
    input_data = np.array([[height, weight, foot_size]])
    prediction = clf.predict(input_data)
    gender = label_encoder.inverse_transform(prediction)
    return gender[0]
print("ABDUL RAFAY / 2022F-BSE-197 / LAB 05 / TASK 03:\n")
# Example: Predicting for a new entry
new_height = float(input("Enter Height: "))
new_weight = int(input("Enter Weight: "))
new_foot_size = int(input("Enter Foot Size: "))
predicted_gender = predict_gender(new_height, new_weight, new_foot_size)
print(f"The predicted gender is: {predicted_gender}")
# Generating the confusion matrix
conf_matrix = confusion_matrix(y, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)
# Calculating model accuracy
accuracy = accuracy_score(y, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

ABDUL RAFAY / 2022F-BSE-197 / LAB 05 / TASK 03:



Enter Height:  6.5
Enter Weight:  190
Enter Foot Size:  10


The predicted gender is: male

Confusion Matrix:
[[4 0]
 [0 4]]
Model Accuracy: 1.00


In [25]:
# ABDUL RAFAY / 2022F-BSE-197 / LAB 05 / HOMETASK:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder, StandardScaler, PolynomialFeatures
from sklearn.feature_selection import SelectKBest, f_classif
# Load the data
file_path = 'extended_employee_data RAFAY.csv'
data = pd.read_csv(file_path)
# Display the first few rows of the dataset
print("ABDUL RAFAY / 2022F-BSE-197 / LAB 05 / HOMETASK:\n")
print("Dataset Sample:")
print(data.head())
# Data Preprocessing
# Encode categorical variables
le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])  # Male=1, Female=0
data['Position'] = le.fit_transform(data['Position'])
data['Attrition Status'] = le.fit_transform(data['Attrition Status'])  # Active=0, At Risk=1, Left=2
# Features and target variable
X = data.drop(columns=['Employee ID', 'Attrition Status'])
y = data['Attrition Status']
# Feature Engineering: Add Polynomial Features
poly = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)
X_poly = poly.fit_transform(X)
# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_poly)
# Feature Selection: Use SelectKBest to choose the top features
k_best_selector = SelectKBest(score_func=f_classif, k=10)  # Selecting top 10 features
X_selected = k_best_selector.fit_transform(X_scaled, y)
# Split the dataset: Train with all except the last 10 rows, use the last 10 rows for testing
X_train, X_test = X_selected[:-10], X_selected[-10:]
y_train, y_test = y[:-10], y[-10:]
# Train the Decision Tree model
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
# Predictions using the Decision Tree model
y_pred_dt = dt_model.predict(X_test)
# Classification Report
print("Classification Report - Decision Tree:")
print(classification_report(y_test, y_pred_dt))
# Predictions for the last 10 rows
print("Predictions for the last 10 rows - Decision Tree:")
test_data_with_predictions_dt = data.tail(10).copy()
test_data_with_predictions_dt['Predicted Attrition Status (DT)'] = le.inverse_transform(y_pred_dt)
print(test_data_with_predictions_dt[['Employee ID', 'Attrition Status', 'Predicted Attrition Status (DT)']])
# Model Evaluation: Accuracy
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print("\n")
print(f"Decision Tree Model Accuracy: {accuracy_dt * 100:.2f}%")
# Confusion Matrix and Classification Report for Decision Tree
print("Confusion Matrix - Decision Tree:")
print(confusion_matrix(y_test, y_pred_dt))

ABDUL RAFAY / 2022F-BSE-197 / LAB 05 / HOMETASK:

Dataset Sample:
   Employee ID  Age  Gender    Position  Years at Company  Monthly Salary ($)  \
0         1001   30    Male    Engineer                 5                6000   
1         1002   45  Female     Manager                10               10000   
2         1003   27    Male  Technician                 2                4500   
3         1004   38  Female    Engineer                 7                6800   
4         1005   50    Male     Analyst                12                8000   

   Performance Rating  Training Hours  Satisfaction Level (%) Attrition Status  
0                   4              20                      75           Active  
1                   5              15                      80           Active  
2                   3              10                      65          At Risk  
3                   4              25                      85           Active  
4                   2               5     